title:        Dushyant Mehta
tagline:      Computer Vision and Machine Learning Stuff
description:  'Work and ramblings'
url:          http://mehtadushy.github.io/
version:      1.0

comments:	  true

markdown: kramdown

highlighter: null

author:
  name:       'Dushyant Mehta'
  email:      'dmehta@mpi-inf.mpg.de'


permalink:    pretty

paginate:     5

exclude: [untracked_dump]

#
# We specify the directory for Jekyll so we can use @imports.
#sass:
#  sass_dir:          _sass
#  style:            :compressed
