title:        Dorsal Stream
tagline:      Dorsal Stream (and Ventral)
description:  'Some Computer Vision and Machine Learning Musings, Peppered with Occasional Off-topic Philosophical and Non-sensical Ramblings'
url:          http://mehtadushy.github.io/
version:      1.0

highlighter:

author:
  name:       'Dushyant Mehta'
  email:      'dmetha@mpi-inf.mpg.de'


permalink:    pretty
relative_permalinks: true

paginate:     5

exclude: [postDump]

#
# We specify the directory for Jekyll so we can use @imports.
#sass:
#  sass_dir:          _sass
#  style:            :compressed
