title:        Dorsal Stream
tagline:      ML & CV thoughts, ideas, and rants
description:  'Computer Vision and Machine Learning ~~Coming Soon~~'
url:          http://dorsalstream.net/
version:      1.0

comments:	  true

markdown: kramdown

highlighter: rouge

author:
  name:       'Dushyant Mehta'
  email:      'dmehta@mpi-inf.mpg.de'


permalink:    pretty

paginate:     5

plugins:	  [jekyll-paginate]

exclude: [untracked_dump]

#
# We specify the directory for Jekyll so we can use @imports.
#sass:
#  sass_dir:          _sass
#  style:            :compressed
